### ISSUE TITLE
Hi and can we create a package? :)

### ISSUE THREAD

**Issue by marimeireles** [ckw017/vader-sentiment-rust#3]
Hello @ckw017. Thanks for your work with the bindings!
I started to use vader rust and I intend to do some upkeeping and even some updates once I feel more comfy with the language.
I'd like to start by uploading it to cargo, would you be okay with that?

I've never done it before, but I can give you all the maintainer positions and so on =)
Just would like to make it easier to use!

Cheers!

**Comment by ckw017** [comment]
Sounds good to me, I just added you as a collaborator on the repo. As you might've noticed this project isn't being actively maintained, so feel free to go ahead and upload to cargo if you want to take over
