### ISSUE TITLE
Publish a new release on crates.io

### ISSUE THREAD

**Issue by jqnatividad** [ckw017/vader-sentiment-rust#7]
Hi @marimeireles @ckw017,

Thanks for this library!  It's working quite well for my use case, however, the debugging println!s that were removed in https://github.com/ckw017/vader-sentiment-rust/pull/6 are still on the version published on crates.io.

Can you publish a new version on crates.io?

Thanks again!

**Comment by jqnatividad** [comment]
Howdy @marimeireles @ckw017 , just pinging again to see if you update the release on crates.io.

Thanks!

**Comment by ckw017** [comment]
Sorry, don't think I have access the package on crates.io. @marimeireles can you update the release and/or help me get access?

**Comment by marimeireles** [comment]
Sorry peeps. I'm kinda out. I'll look into it later tonight.

**Comment by marimeireles** [comment]
And I can give you access, yes, I think you need an account on crates.io :)
Just give me your username

**Comment by jqnatividad** [comment]
I believe @ckw017's github id is all you need per

https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

**Comment by marimeireles** [comment]
Sorry for the delay peeps, I was going through a complete offline phase :)
Coming back now, it's released and I'll add @ckw017 as a maintainer there too
Thanks for the patience!

**Comment by marimeireles** [comment]
But I do need @ckw017 to create an acc ;)

```
zsh: command not found: $
 ✘  ~/dev/vader-sentiment-rust   master  cargo owner --add ckw017
    Updating crates.io index
error: failed to invite owners to crate `vader_sentiment` on registry at https://crates.io

Caused by:
  the remote server responded with an error: could not find user with login `ckw017`
  ```

**Comment by ckw017** [comment]
Ah, my bad. Account is set up on crates.io now, https://crates.io/users/ckw017

**Comment by ckw017** [comment]
> Sorry for the delay peeps, I was going through a complete offline phase :)

No worries! Once crates.io is set up should be easier to load balance for this kind of situtation
